import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";

const fontSans = Inter({
  variable: "--font-sans",
});

const fontSerif = Roboto({
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
