import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { QueryProvider } from "@/components/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";


const fontSans = Inter({
  variable: "--font-sans",
});

const fontSerif = Roboto({
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} antialiased`}
      >
        <ThemeProvider>
          <QueryProvider>
            {children}
            <Toaster />
            <ReactQueryDevtools initialIsOpen={false} />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
